### ISSUE TITLE
Integreation with The Landscape of Immuno-Oncology Drug Development

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/shiny-iatlas#120]
From Vésteinn:

Hi everyone, 

Based on discussions yesterday, we would like to look into ways to enable researchers to relate content between two CRI funded efforts
 - The Landscape of Immuno-Oncology Drug Development resource ( Clinical Accelerator team @ CRI ) 
- CRI iAtlas (Sage Bionetworks , Institute for Systems Biology).  

We would like to start discussion of integration in the longer term, but in the short term we would like to initiate things with a pilot project as follows

Pilot project connecting iAtlas and IO Drug Development Resource
Three basic components

1. Include genes in the IO target base in the “Immonomodulator” module of CRI iAtlas (or produce a similar,separate, module). Genes are in the attached spreadsheet.

2. Currently when someone selects a target in IO Drug user interface (UI), a pop-up is displayed. In the current ‘pop-up’ on the UI, include “Explore Molecular Changes”. The corresponding Gene ID (or IDs) will be sent as a query to iAtlas, which will then display the gene expression for the selected gene(s)

3.  iAtlas will allow “See clinical trials” for a particular gene selection. IO target resource will need to be ‘receive’ a Gene ID query and to display info based on that.

These are some basic ideas and it will be fun to discuss how to work them out. Please share ideas here ( or opt out as we get in to the more technical details)

Vésteinn

PS Hmm, now wondering if we can we also make use of information in the IO drug resource as to which cancer tissues the trials are directed at.

**Comment by vthorsson** [comment]
Discussion moved to planning repo.
