### ISSUE TITLE
Prioritize suggestions from conference

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/shiny-iatlas#121]
Decide which of these to work on:

* allow search for any gene , not only immunomodulators
* recieve notifications of major versions
* Include normal tissue for comparison
* upload your own gene sets and score those - example a particular dendritic cell signature
* See more details of genes sets in Data description
* From a summary barchart download e.g. the means and std devs
* more info on tcga subtypes  - e.g. originating manuscript
* Include mouse data

**Comment by vthorsson** [comment]
Moved to planning repo to work on there.
