### ISSUE TITLE
Carry TCGA subtype colors into app when available 

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#131]
![image](https://user-images.githubusercontent.com/2837859/47458736-2ff9df00-d78f-11e8-8e3a-ce6f332fa14c.png)

tcga_subtype colors do not seem to be carried into the app from sample_group_df$FeatureHex

**Comment by vthorsson** [comment]
@andrewelamb  ,are there fields in two objects that store color? In addition to the above, am seeing panimmune_data$tcga_subtype_colors.   Perhaps the latter is the one that is relevant for use?

**Comment by andrewelamb** [comment]
@vthorsson 

panimmune_data$tcga_subtype_colors is indeed what is used everywhere in the app(AFAIK)
