### ISSUE TITLE
Fix Clinical Outcomes when ploting TCGA subtypes

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/shiny-iatlas#132]
Certain TCGA subtypes such as 'AML' cause errors like:

'names' attribute [8] must be the same length as the vector [4]

When the Clinical Outcomes module attempts to create a kmplot. These seem to be smaller groups and may need to handled as an error.

**Comment by Gibbsdavidl** [comment]
ok, getting to this

**Comment by Gibbsdavidl** [comment]
OK, looks like one of the subtypes of AML doesn't have a member with status ==0 ... might be causing it... here's a table with counts of each status for each subtype.  Can probably fix this early tomorrow.

# A tibble: 8 x 3
  variable  Num1  Num0
  <fct>    <int> <int>
1 AML.         6     2
2 AML.1       12     0
3 AML.2       14     5
4 AML.3        5    13
5 AML.4       21    15
6 AML.5       20    13
7 AML.6       19     9
8 AML.7       14     6

**Comment by Gibbsdavidl** [comment]
I have narrowed it down to the call to create_kmplot... in particular, the error happens when risk.table = T.  Still trying to puzzle out how to catch it...

survminer::ggsurvplot(
    fit,
    data = df,
    conf.int = F,
    risk.table = T,
    title = "title",
    palette = group_colors
)

**Comment by Gibbsdavidl** [comment]
The second error, in the heatmap, comes from the ci_mat matrix, which is all NaNs.

Several of the features (columns) in LAML, are all NAs ...

**Comment by Gibbsdavidl** [comment]
FIXED the color bug!

Problem was the survival fit appended the subtype names with the column name, "variable=", and then the plot function needed palette to be a named vector --- matching the subtype names --- like 'variable=LAML.1'

**Comment by Gibbsdavidl** [comment]
The second bug in the heatmap ... I think just comes from some TCGA studies that have missing info in the feature matrix.... can maybe just catch it and display a message.
