### ISSUE TITLE
Custering model missing for Immune Subtype Predictor

### ISSUE THREAD

**Issue by Jasonliu21** [CRI-iAtlas/shiny-iatlas#135]
There is no clustering model data "data/wolf_set_slim1.rda” needed for "Immune Subtype Predictor" in  data folder

**Comment by Jasonliu21** [comment]
Warning in readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/wolf_set_slim1.rda', probable reason 'No such file or directory'
Warning: Error in readChar: cannot open the connection

**Comment by vthorsson** [comment]
Fixed.
