### ISSUE TITLE
Possible failure of Clinical Outcome module on Custom Sample Group

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#138]
Sample Group Survival report error on an example file

https://raw.githubusercontent.com/CRI-iAtlas/shiny-iatlas/develop/data/example_user_group2.csv

selecting COAD

Loading of file,  and other modules appear normal.

**Comment by vthorsson** [comment]
@Gibbsdavidl can you help evaluate the status of this and tag/close/assign accordingly. Thanks

**Comment by Gibbsdavidl** [comment]
Oh, fixed it!
The fix and some improvements are in the surv_group_fix branch.

**Comment by Gibbsdavidl** [comment]
Would be good if someone tested it.

**Comment by andrewelamb** [comment]
@Gibbsdavidl This fix is conflicting with the current develop branch. Could you merge develop into your surv_group_fix branch and resolve that?

**Comment by vthorsson** [comment]
Did the test on `surv_group_fix` branch and it looks good to me
