### ISSUE TITLE
README refers to a deprecated method for deployment

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#139]
Suggested deployment method still works, but may not work for long. Would be better to suggest a  BiocManager  equivalent

```
> options(repos = BiocInstaller::biocinstallRepos())
Warning message:
'BiocInstaller' and 'biocLite()' are deprecated, use the 'BiocManager' CRAN
  package instead.
```

**Comment by andrewelamb** [comment]
Might need to use: BiocManager::repositories()

**Comment by vthorsson** [comment]
This is issue is will likely be close with introduction of `renv`

**Comment by vthorsson** [comment]
We have new readme in `development` branch so closing this
