### ISSUE TITLE
Concordance Index in clinical outcomes not working

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#140]
Concordance Index in clinical outcomes seems not to be generating results. Tried multiple selections of variables.

**Comment by andrewelamb** [comment]
@vthorsson 

This check makes no sense, and is the source of the issue.

validate(
          need(nrow(ci_mat[!is.na(ci_mat)]) > 0, "No results to display, pick a different group.")
        )

**Comment by andrewelamb** [comment]
Replaced with:

validate(
          need(nrow(ci_mat[rowSums(is.na(ci_mat)) == 0,]) > 0, "No results to display, pick a different group.")
        )
