### ISSUE TITLE
PAAD missing from list

### ISSUE THREAD

**Issue by Gibbsdavidl** [CRI-iAtlas/shiny-iatlas#142]
Looks like PAAD is missing from the drop down menu at the sample overview.

But it's shown in the all-study plot.

**Comment by vthorsson** [comment]
Can you give some more steps?  Not understanding what is meant - Thnx

**Comment by andrewelamb** [comment]
I'm also unclear on what the issue is.

**Comment by vthorsson** [comment]
@Gibbsdavidl , can you describe how to get to this error. Thanks

**Comment by vthorsson** [comment]
@Gibbsdavidl , is this still a problem? Was not able to find this or reproduce. Thanks
