### ISSUE TITLE
Immunomodulator data file - multiple values

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#143]
The file `im_expr_df` has instances where more than one gene expression levels is given
```
filter(im_expr_df,ParticipantBarcode=="TCGA-BH-A1FC",Symbol=="IL13")
# A tibble: 2 x 3
  ParticipantBarcode Symbol normalized_count
  <chr>              <chr>             <dbl>
1 TCGA-BH-A1FC       IL13              0.588
2 TCGA-BH-A1FC       IL13              6.51
```
Digging into this it turns out that this due to expression values in the expression matrix (EB++) being available available aliquots, and that participant barcode has not been associated with the representative Aliquot. 

```
TCGA-BH-A1FC-01A-11R-A13Q-07 TCGA-BH-A1FC-11A-32R-A13Q-07
IL13                       0.5885                       6.5089
```
The representative Aliquot is `TCGA-BH-A1FC-01A-11R-A13Q-07` so only 0.5885 should be in `im_expr_df`

**Comment by vthorsson** [comment]
Attached candidate replacement file

[im_expr_df.feather.gz](https://github.com/CRI-iAtlas/shiny-iatlas/files/3364230/im_expr_df.feather.gz)

**Comment by andrewelamb** [comment]
@vthorsson I noticed the same issue and will move this to the repo

**Comment by vthorsson** [comment]
Uploaded replacement file may still have had issue with duplicates
New candidate file recreated
[im_expr_df.July2019.feather.gz](https://github.com/CRI-iAtlas/shiny-iatlas/files/3811196/im_expr_df.July2019.feather.gz)

md5 e4725bc679755c480e1ab5ae84c93420 
( un-gz'ed)

+ @heimannch , will you be able to sanity check

**Comment by heimannch** [comment]
This file meets what we are currently testing for:
- there are no duplicated rows;
- I was able to merge expression data with the `GenExp_All_CKine_genes.tsv` from the `cytokine-network-dev` repo.

**Comment by vthorsson** [comment]
Good to hear @heimannch , and thanks for checking.  Please use this version in your branch for later merge into develop.

**Comment by heimannch** [comment]
As I was preparing the file to include it as the `im__expr_df.feather` file, I've noticed that there are 228 participants IDs missing from this new version, such as:

````
  ParticipantBarcode
  <chr>             
1 TCGA-06-0681      
2 TCGA-44-6144      
3 TCGA-55-6969      
4 TCGA-91-6831      
5 TCGA-BR-7704      
6 TCGA-EJ-A8FO 
````
Full list of missing participantsBarcodes in `im_expr_df.July2019.feather.gz`, when compared to `im_expr_df.feather` in the develop branch: [missing_partID.csv.gz](https://github.com/CRI-iAtlas/shiny-iatlas/files/3849203/missing_partID.csv.gz)

It is also worth mentioning that this doesn't affect the `cytokine_network` repo and issue #155, as none of the missing ParticipantBarcode is present in the data in `GenExp_All_CKine_genes.tsv`.

**Comment by vthorsson** [comment]
@heimannch I believe those barcodes are ones that do not have a `Representative_Expression_Matrix_AliquotBarcode`, thus values that may have been filtered for some other reasons.  Are you able to check that ?

**Comment by heimannch** [comment]
Yes, all those barcodes do not have a `Representative_Expression_Matrix_AliquotBarcode`. There are in total (from `fmx_df`) 1387 barcodes missing this annotation, and only those 228 remained in the `im__expr_df.feather` file. I assume that the other 1159 were filtered in some previous step. 

If the immunomodulators gene expression data is supposed to have barcodes that have a `Representative_Expression_Matrix_AliquotBarcode`, the file `im_expr_df.July2019.feather.gz` is ok to be used.

**Comment by vthorsson** [comment]
Yes, correct , we are currently requiring that expression data shown in the app have a `Representative_Expression_Matrix_AliquotBarcode`, so looks like we are good. Thanks for checking this, @heimannch

**Comment by heimannch** [comment]
Great! I just pushed a commit (4641f098522d1bca6ff5fef87df53cd0b7d52828) to the `cytokine-network` branch updating the file.

**Comment by vthorsson** [comment]
@heimannch Please close this issue if you think that is appropriate. Alternately we could keep an eye on it for the release (there is even a label for that !)

**Comment by heimannch** [comment]
I believe it is better to wait until the updated file is merged into develop before closing this issue. Let's keep an eye on it!

**Comment by vthorsson** [comment]
75 genes and 9693 participants for a total of 
726,975 rows (ParticipantBarcode, Symbol, normalized_count)

**Comment by andrewelamb** [comment]
@vthorsson All other issues have been resolved, could you confirm this has been merged into develop?

**Comment by vthorsson** [comment]
@heimannch are you able to work with @andrewelamb to get the version you have into 1.2 ? (we know it would make it into 1.3)

**Comment by heimannch** [comment]
The updated immunomodulator data file is now in the develop branch.I will close this issue.
