### ISSUE TITLE
More clarity / options on correlation metrics

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#149]
Thanks for providing this very useful interface to cancer data! I'd like to suggest a feature that might be useful for the plot on the right:

Briefly, there are different kinds of correlation one might want to evaluate. I assume your correlations as represented are Pearson correlations? If you also support Spearman correlation, which doesn't depend as strongly on the linearity of the correlation, and a corresponding plot of the ranked x and y axes, this would be more informative in some cases. In particular, in the image above, it isn't clear whether the lack of high leukocyte fraction, high mast cell fraction data is below what is expected from the product of the low overall frequency of those parts of the leukocyte and mast cell fractions. A rank plot and Spearman correlation would address this kind of pattern.

Thanks!

(Received via iAtlas help/suggestions email )

![image](https://user-images.githubusercontent.com/2837859/61318432-ea1bf580-a7b9-11e9-9133-5e29ebd2bef3.png)

**Comment by andrewelamb** [comment]
@vthorsson The current module allows you to select from the different correlation methods, so I assume this is an older request? The rest of the e-mail is a little unclear to me what they are asking for, is there anything else to be done here?

**Comment by vthorsson** [comment]
Yes, indeed @andrewelamb , I appear to have started an issue on something has been taken care of already!
