### ISSUE TITLE
Log scale display or log-transformed data needed for some variables display in violin plots

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#150]
The default non-logged view is not helpful for Immune Feature Trends violin plots for variables such as mutation rates and neoantigen counts

![image](https://user-images.githubusercontent.com/2837859/61403356-0a1aea00-a88a-11e9-9fd6-159558cc6a69.png)

**Comment by andrewelamb** [comment]
@vthorsson Please try the submodules branch to take a look.
