### ISSUE TITLE
TIL image viewer down.

### ISSUE THREAD

**Issue by Gibbsdavidl** [CRI-iAtlas/shiny-iatlas#151]
http://quip1.bmi.stonybrook.edu:443/camicroscope/osdCamicroscope.php?tissueId=TCGA-AR-A252-01Z-00-DX1

**Comment by Gibbsdavidl** [comment]
From the link on TIL map annotations.

**Comment by vthorsson** [comment]
It looks like http ---> https might fix it

**Comment by vthorsson** [comment]
Fixed, with fix as suggested.
