### ISSUE TITLE
Immune trends correlation issue

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/shiny-iatlas#152]
When the response variable is part of the selected variable class, there is an error. Does it make sense to allow this?

**Comment by vthorsson** [comment]
Agree. That combination should not be an allowed choice.

**Comment by vthorsson** [comment]
@andrewelamb , do we know if this is still happening (on the branch that will go into the next release?)

**Comment by andrewelamb** [comment]
@vthorsson This has been fixed in https://github.com/CRI-iAtlas/shiny-iatlas/tree/fix/#163

**Comment by vthorsson** [comment]
OK thanks. Added a `keep-an-eye-on-it`  so that we can check that it is OK in the loaded app. Feel free to modify that and/or close

**Comment by vthorsson** [comment]
Ok looks good in `fix/#163` .  ( If the user selects this way, the variable is dropped from the row display)
