### ISSUE TITLE
Include friendly-name option for receptors and ligands in cytokine network

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#158]
Allow user to display friendly names for receptors and ligands, as available in 

https://docs.google.com/spreadsheets/d/1aqOXYsU1ubkbxIZI_5p8ZRootgOAT0KweMA3LvSZ7HY/edit#gid=0

**Comment by heimannch** [comment]
Current version of the module, in respect of displaying the Friendly Names for genes is the following:
- search and selection, and node lookup support Friendly Names for immunomodulators
- network displays nodes with their HGNC symbol
- Nodes tables contain a column for HGNC ID and Friendly Name

We can update this feature as we expand the annotation of Friendly Names for genes other than the immunomodulators.

**Comment by vthorsson** [comment]
@heimannch , hopefully v1.2 Milestone is correctly identified

**Comment by heimannch** [comment]
Current version of the network visualization: 
- search and selection, and node lookup support HGNC and Friendly Names for immunomodulators;
- network displays nodes with their Friendly Names (when available);
- Nodes and Edges tables contain a column for HGNC ID and Friendly Name.

**Comment by vthorsson** [comment]
Looks good @heimannch , thanks for including those.
