### ISSUE TITLE
Make it clear selection box also includes incremental string search (e.g. Variables in Immunomodulator Module)

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#162]
Should be mentioned in a text description that drop-down selection boxes also include search, in cases where it is helpful. For example 
Gene selection in Immunomodulator module
Options include
- changing title of drop-down "Select or Search for Variable" instead of "Select Variable"
- including in the text descriptions

**Comment by andrewelamb** [comment]
@vthorsson please checkout https://github.com/CRI-iAtlas/shiny-iatlas/tree/fix/#163

This was accidentally commited with the fix to issue #163 

I relabeled all the select buttons where searching might be useful(ie. more choices than can appear in the dropdown)

**Comment by vthorsson** [comment]
OK, thanks @andrewelamb.  Is the the new version currently in `develop` (I am looking at the Immunomodulator module "select variable"  as an example )

**Comment by vthorsson** [comment]
@andrewelamb , now looking in `fix/#163`and see new label "Select or Search for Variable" for the immunomodulator module . Looks good.
