### ISSUE TITLE
Row order of the heatmap in the Correlations section of Immune Feature Trends

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#163]
For the public app, the row order of the heatmap in the Correlations section of “Immune Feature Trends” has changed. It had previously been ordered in a specified way, to be consistent with a manuscript panel. 

Figure shows order in the intended way, for variable class DNA Alteration, Response Variable Leukocyte Fraction, and Immune Subtypes. The live app instead has the following rows from top “Intratumor Heterogeneity”, “SNV Neoantigen”, “Number of Segments”, …

![image](https://user-images.githubusercontent.com/2837859/70561614-a4ccdb80-1b3f-11ea-965d-4df05021ec37.png)

**Comment by andrewelamb** [comment]
@vthorsson please checkout https://github.com/CRI-iAtlas/shiny-iatlas/tree/fix/#163

**Comment by vthorsson** [comment]
@andrewelamb , not sure how to do that.  The above link is gives a 404 page not found.

**Comment by vthorsson** [comment]
OK looks good in `fix/#163`

![image](https://user-images.githubusercontent.com/2837859/73142055-48664280-403f-11ea-81fa-6775746bd761.png)
