### ISSUE TITLE
Cell image module finished

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/shiny-iatlas#171]

**Comment by heimannch** [comment]
- [ ] Finalize methods text and driving instructions
- [ ] Include the legend with the color ranges
- [ ] Display select group drop-down with TCGA Study alphabetically sorted
- [ ] Integrate abundance data into load_data files (merge with cytokine-network)
- [ ] Convert annotations currently in txt and tsv to feather files
- [ ] Adapt module to take in custom groups (adapt code from cytokine-network)
- [ ] Merge develop into the cell-image branch
- [ ] Make sure that dependencies are covered by the renv install (?)

**Comment by heimannch** [comment]
@vthorsson , last commit to `ecn-cellimage-for-merge` has all the items in the checklist above. Please let me know if there is anything else you would like to include/change in the module before closing this issue.
