### ISSUE TITLE
shiny::runTests()

### ISSUE THREAD

**Issue by alandipert** [CRI-iAtlas/shiny-iatlas#193]
Hello all, I just wanted to drop a pointer to some experiments I've been doing on a fork, in case they ever are useful: https://github.com/alandipert/shiny-iatlas. I learned about the app at the Shiny BoF at rstudio::conf back in January.

I've been experimenting with a few different upcoming Shiny features in the context of this app: the `moduleServer()` and `runTests()` functions in particular. There is a new `R/` autoloads feature, but I'm not sure it's applicable to your app organization because it loads code in sort order and there isn't yet to define the collation order a la packages.

Anyway, thanks for making your app public. I really appreciate that you use `renv` and have a nice README; it was really easy to get set up locally 😄 

I didn't think a PR was appropriate since the Shiny features aren't released yet, but I'm happy to answer questions you might have about the changes I made. I'll keep my fork around for reference.

**Comment by andrewelamb** [comment]
Hi Alan! This is Andrew, we talked at the BoF :)

A lot of our development is going into a new [repo](https://github.com/CRI-iAtlas/iatlas-app). In fact we have an issue for [this](https://github.com/CRI-iAtlas/iatlas-app/issues/5)!

I am definitely still interested in implementing it once it's released. Maybe we should chat at some point?

I hope iAtlas was a useful test case!

**Comment by alandipert** [comment]
Hi Andrew!

Yes, a chat sounds good. Feel free to drop me a note at alan@dipert.org and we can make arrangements. Looking forward to it 👍
