### ISSUE TITLE
Update IO Target Module with Fall 2020 data update

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#200]
31 genes with annotations included @annieyucri in the google drive doc `IO_targets`, corresponding to the new manuscript 

https://www.nature.com/articles/d41573-020-00166-1

Need to 
- Identify genes for which expression is available
- Update `data/io_target_expr_df.feather` with the expression of those genes
- Update annotations loaded via `data/io_target_annotations.feather`
- Update static text on `data/markdown/io_target.markdown` to include the new publication

**Comment by vthorsson** [comment]
First round of changes implemented in branch `io-target-fall2020-data-update`

**Comment by heimannch** [comment]
Data updated in the v1.3.1.
