### ISSUE TITLE
data/io folder is missing

### ISSUE THREAD

**Issue by daxiagithub** [CRI-iAtlas/shiny-iatlas#208]
Here is the error message I got:

```
> shiny::runApp()
`summarise()` regrouping output by 'ParticipantBarcode' (override with `.groups` argument)
 Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="data/io/fmx_io.feather": The system cannot find the path specified 
```

Thanks!

**Comment by vthorsson** [comment]
Thanks for the error report @daxiagithub .  @heimannch  would you be able to take an initial look at this? (I can see a somewhat similar path error on my local install )

**Comment by heimannch** [comment]
@daxiagithub thanks for bringing this to our attention. I just added the files, let us know if you have any comments or run into any issue!

**Comment by daxiagithub** [comment]
Thank you very much, @vthorsson and @heimannch !  The app is running now.  You may want to update your 1.4.0 release file too.

A related question.  Is "shiny-iatlas" the default deployment now?  What about "iatlas-app" + "iatlas-data" version?  What are the differences between the two?

**Comment by heimannch** [comment]
Glad to know you were able to run the code locally, @daxiagithub!

And yes, `shiny-iatlas` is the current version deployed at https://isb-cgc.shinyapps.io/shiny-iatlas/. 
`iatlas-app` contains the code of an upcoming release of the app, with new and improved features (that also hopefully will avoid the type of issue that you just reported!) 

I will close this issue, but please feel free to send us any question or comments.
