### ISSUE TITLE
Allow access to full IO expression set from app

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#210]
Expression download currently has immunomodulator expression only. Full expression set would be preferable. 

Before closing this issue, be sure it is mirrored in 2.0

**Comment by vthorsson** [comment]
A file to share would be https://www.synapse.org/#!Synapse:syn21123525 (currently in non-public space), according to @DanteBortone . One option might be to move that to a location in https://www.synapse.org/#!Synapse:syn10337516/wiki/458420 and link to it

**Comment by heimannch** [comment]
Link to Synapse added to v1.4.1: https://www.synapse.org/#!Synapse:syn24200710
Link already added to 2.0.
