### ISSUE TITLE
can I use my own subtype tcga data to analyse immune features difference?

### ISSUE THREAD

**Issue by worker000000** [CRI-iAtlas/shiny-iatlas#215]
Dear professor,
thanks a lot for making such a powerful app.
I found one paper citing your paper

Identification of tumor antigens and immune subtypes of cholangiocarcinoma for mRNA vaccine development
![image](https://user-images.githubusercontent.com/25199946/119267093-dba58d00-bc1f-11eb-9964-d3e5951aa6a2.png)

how should I upload my own subtype tcga data to compare the difference of C1-C6 and immune features?

**Comment by andrewelamb** [comment]
@worker000000 This is the repo that corresponds to the URL you are using.

**Comment by heimannch** [comment]
Hi @worker000000,

Thanks for sending us how you are using the iAtlas app. You can see the visualization of your TCGA custom groups by following these steps:

1 - Upload your custom groups (check **Formatting Instructions** for pointers on how to prepare the file with your custom groups) in the _Sample Group Overview_ module:
![image](https://user-images.githubusercontent.com/32350126/119563259-2c220500-bd5c-11eb-9d7e-dd290cc01bef.png)

2 - After the upload is completed, change the global group settings to the custom group in Explorer Settings in the left menu:
![image](https://user-images.githubusercontent.com/32350126/119563687-ba968680-bd5c-11eb-8738-22e8017b684f.png)

3 - The new sample group will be propagated to modules with TCGA data:
![image](https://user-images.githubusercontent.com/32350126/119564119-43adbd80-bd5d-11eb-98fa-a512af82e314.png)

Please note that the custom TCGA subtypes will be applied to a subset of the modules, as the modules under the **_Molecular Response to ICI_** section provide visualization of other datasets (refer to _ICI Datasets Overview_ for more information):
![image](https://user-images.githubusercontent.com/32350126/119565285-a5225c00-bd5e-11eb-9c5e-90cdc63bee94.png)

Let us know if you have other questions, and thanks for using iAtlas!

**Comment by worker000000** [comment]
Thanks a lot, if I want plot the p.value, is there such function?
and can I compare many features one time?

**Comment by heimannch** [comment]
Hi @worker000000,

In the example above, with the _Immune Feature Trends_ module, you can see only one immune feature at a time for as many TCGA groups as you defined in your sample custom group. There is no option to add p-values in the distribution plot.

The `data` folder in this repo contains the data that is used in iAtlas, in case you are interested in developing your own analysis.  
We are also working on new materials to allow users to run CRI iAtlas modules and visualizations with their own data. We suggest you follow [@iatlas_cri](https://twitter.com/iatlas_cri) on Twitter for latest developments!
