### ISSUE TITLE
Clean up tooltip formatting and info for all plots

### ISSUE THREAD

**Issue by jaeddy** [CRI-iAtlas/shiny-iatlas#50]
Currently just using plotly default tooltips; should be able to control what information is presented in labels (as well as label formatting) either in the corresponding `build_<plot-type>_df` function or in the `create_<plot-type>` function.

**Comment by andrewelamb** [comment]
I accidentally did this one in the process of adding clickable group info to each plot. Each of the plot functions have a label_col argument, if you point to the correct column, these will show up as labels in the plotly plot.
