### ISSUE TITLE
Expand choices of Response variable in Correlations in the Immune Feature Trends Module

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#92]
Need to revisit choices for response variable here. One option might be to allow any continuous variable.

**Comment by vthorsson** [comment]
This is now available in current `user-defined-groups` branch.

**Comment by andrewelamb** [comment]
@vthorsson has this been addressed? If so we should close it. If not let's move it to the new repo?

**Comment by vthorsson** [comment]
Oh yes ! This has indeed been taken care of , perhaps a long time ago. Will close
