### ISSUE TITLE
Limited set of tumor types being displayed for certain choice of variables

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#93]
For the combination of choices 
- TCGA Study
- DNA Alteration a
- Leukocyte fraction
in the Correlation/Immune Feature Trends

only ~17 tumor types are displayed. Check if OK/due to some requirement of minimal/complete  data or if we need to adjust. 

![image](https://user-images.githubusercontent.com/2837859/39948731-2d76c594-552c-11e8-9465-99e95a03642a.png)

**Comment by jaeddy** [comment]
Fixed by @andrewelamb in 7f33acc1ac3b77f7643aae039d2a4ad740017c2e
